checks/style_needed.php

Six years ago, `.screen-reader-text` was introduced as a canonical class name for text targeted to screen readers for all of core.
Unknown to many, this includes the front-end by virtue of its use in `get_search_form()`.
To ensure forward compatibility with future a11y improvements, and be able to deal with child themes adding theme support for HTML5 features which rely on that class heavily, all themes should have it defined to deal with assistive text.
See https://core.trac.wordpress.org/ticket/29699.

Add a check for `.screen-reader-text`.

---

checkbase.php

Can cause a PHP warning, failed to open stream: No such file or directory in themes that reference a file that is not actually there.

Check if the file exists before opening it.

---

checks/content-width.php

`_s` uses now `$GLOBALS['content_width']` instead of `$content_width`
https://github.com/Automattic/_s/pull/460

Add check also for `$GLOBALS['content_width']`

---

checks/badthings.php
checks/basic.php
checks/constants.php
checks/filenames.php
checks/i18n.php
checks/iframes.php
checks/include.php
checks/lineendings.php
checks/links.php
checks/malware.php
checks/more_deprecated.php
checks/nonprintable.php
checks/phpshort.php
checks/post-formats.php
checks/required.php
checks/screenshot.php
checks/searchform.php
checks/style_suggested.php
checks/style_tags.php
checks/suggested.php
checks/textdomain.php
checks/time_date.php
main.php

In the next version of WordPress (4.4), we fixed many translation strings that used html tags.
See: https://core.trac.wordpress.org/query?milestone=4.4&component=I18N&reporter=ramiy&group=milestone&col=id&col=summary&col=milestone&col=type&col=priority&col=component&col=severity&col=resolution&order=priority
The same thing should be done in this plugin. 
It's make it much easier to translates those strings. Removing the code, I can translate only the text.

Avoid using HTML tags in translation strings

---

checks/commpage.php

`the_comments_navigation` is supported since a few days but `the_comments_pagination` is still missing

add support for the_comments_pagination

---

checks/title.php

The semicolon at the end of a call to `wp_title()` should be optional. Currently, this fails: 
````
<title><?php wp_title() ?></title>
````
Theme Check should not trigger an error for the above.

Semicolon should be optional in wp_title()

---

checks/style_needed.php

Fixes #130 I added a simple check for the presence of Text Domain: into the existing Style_Needed check. The other checks there checks that the line has the proper beginning, but doesn't validate the format of the rest of the line. This pull request mimics that, but could this be extended or is there a reason not to check the rest of the line?
If the rest of the line was checked, for checking the text domain it might be something more like
`[ \t\/*#]*Text Domain:\s*[A-Za-z0-9-]+\n`
where it confirms there is no underscore used. I haven't looked to see exactly how that's parsed yet so would do that before extending the regular expression.

Check for Text Domain in style.css - Fixes #130

---

checks/constants.php

Make the theme check fails themes that use not to be used constants.

Change constants to be required

---

checks/title.php

This PR makes the use of `add_theme_support('title-tag')` required and not just recommended as it was released in WP 4.1 in December 2014.
This also changes from `<title>` tags and `wp_title()` being required to not allowed as `add_theme_support('title-tag')` has been added. `wp_title()` was nearly deprecated. http://wptavern.com/wordpress-4-4-to-deprecate-the-wp_title-function

Title tag check changes

---

checks/textdomain.php

As the TRT Requirement allows a maximum to two text domain, the check should fail if there are more than 2 text domains.
Now there is also a check that the correct text domain is used so to make use of langauge packs

Make text domain checks stricter

---

checks/included-plugins.php

Addresses #134 
Checks for and .zip files present in the repository and throws an error on finding one.

Adding check for included .zip files

---

checks/adminbar.php

This check tries to implement https://github.com/Otto42/theme-check/issues/127
I didn't implement a check for `$show_admin_bar`, because if I understand correctly, variables are not allowed in theme and this will be checked separately?

Check, if theme hides adminbar

---

checks/tags.php

Tags can be output using `the_taxonomies()`.
Fixes #196

add the_taxonomies function

---

checks/style_tags.php
main.php
readme.txt
theme-check.php

Update the plugin on github to match the latest version that is live in the plugin directory.
Issue #214

Update to the latest live version

---

checks/filenames.php

Change the must have to REQUIRED.
Move readme.txt from Recommended to Required.
The readme.txt file is required as of October 25th, 2018.
The link to Required is https://make.wordpress.org/themes/handbook/review/required/#readme-txt-file

Change readme.txt to must have

---

checks/filenames.php
checks/included-plugins.php
main.php

It fixes the following notice, 'Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in D:\root\test\wp3\wp-content\plugins\theme-check\main.php on line 55'.

Fixes a deprecation notice on PHP 7.4

---

checks/cdn.php

Some search patterns were too specific to catch all the cases.
Output as Required, since it is, but leave the return value as okay since it could have false positives.

generalize CDN list

---

checks/nonprintable.php

As `$ret` is set to `true` this will fail the check. The text should show that too by marking as required and not just info.

This check fails - it should be marked as required

---

checks/plugin-territory.php

Fixes issue reported in https://wordpress.org/support/topic/filter-that-contain-string-add_shortcode

Make the add_shortcode slightly stricter

---

checks/plugin-territory.php

This PR adds a few actions and filters I recently encountered in a few of my reviews. 
Filters: 
* `mime_types`, `upload_mimes`
* `user_contactmethods`
Actions:
* `wp_dashboard_setup`, ([example](https://themes.trac.wordpress.org/browser/business-lander/1.1.11/inc/dashboard-widget.php#L12))
Can be tested by adding this in a theme:
```
add_action( 'wp_dashboard_setup', function() {} );
add_filter(  "upload_mimes" ,  function( $mimes ) { return $mimes; } );
add_filter ('user_contactmethods',function( $methods ) { return $methods; } );
```

Plugin Territory - Actions & Filters

---

checks/basic.php

Addresses: #209.
This PR adds a check for wp_body_open to the basic.php check since it is a similar requirement to wp_head and wp_footer which are also found in this file.
If, however, it belongs in a separate file, please let me know and I will move it. Also should I expand the regex to ensure that wp_body_open does actually come immediately after `<body...>`?
We will also need to add an explanation at https://codex.wordpress.org/Function_Reference/wp_body_open or maybe someone can point me to a better url?

Add check for wp_body_open.

---

checks/adminbar.php

Warn for hiding the adminbar. Also adds file names and line numbers.
Setting this to a warning instead of required lets theme authors check if the admin bar is visible or not
(Useful for example to change position of elements below the bar).
Returns true, so that upload is not blocked.
Solves #163

Warn for hiding the adminbar

---

checks/underscores.php

For #169
Note that this check uses **require**, not notice. This is because of an increasing number of 
clones of underscores, where the author has not completed the theme.

Check if the theme is a copy of underscores

---

checks/navmenu.php

This will need a lot of testing before it can be merged.
I was not able to use the regex shared in the issue #142
Instead, the check is trying to look for the content inside `wp_nav_menu()`
It is not limited to usage of the `array()` format, as the suggested regex was.
It tries to check if the arguments are placed outside the `wp_nav_menu()`, and warns 
that the user needs to do a manual check for theme_location.

Check for theme_location and menu name

---

checks/style_tags.php

Move the checks into the loop.
Output the folder name when Tags are missing.
The master is missing the 2 new Tags wide-blocks and block-styles, but the version I got from the .org repo had them, so they are in this PR.

allow for multiple style.css files

---

checks/themename.php

Solves #106 
-Now allows exceptions for existing themes with the words theme and WordPress in the names.

Add check for disallowed theme names

---

checks/plugin-territory.php

Fix for:
`Parse error: syntax error, unexpected ')' in \wp-content\plugins\theme-check\checks\plugin-territory.php on line 117`

Fix for the parse error in plugin-territory.php

---

checks/filenames.php

These changes add Loco Translate's compatibility XML file to the allowlist and extend the allowlist check functionality to support an array of (possible) filenames.

Add Loco Translate's compatibility XML file to allowlist

---

checks/admin_menu.php

Can be tested using:
```
add_action( 'admin_menu', function() {
add_users_page( 'tt', 'tt', 'edit_theme_options', 'tt', '' );
add_menu_page( 'tt', 'tt', 'edit_theme_options', 'tt', '' );
add_pages_page( 'tt', 'tt', 'edit_theme_options', 'tt', '' );
} );
```
Regarding: https://github.com/WordPress/theme-check/issues/260#issuecomment-667122712

Fixed REQUIRED message for admin_menu.php check

---

checks/postthumb.php

The actual change is at the end of line 19.  Github added a newline at the end of the file as there was no newline at the end in the original file.

Adds a missing space

---

checks/style_needed.php
checks/style_suggested.php

Moves 
```
.sticky
.bypostauthor
.alignleft
.alignright
.aligncenter
.wp-caption
.wp-caption-text
.gallery-caption
```
to style_suggested.php and make them recommended instead of required.

CSS classes: Reduce level from required to recommended

---

checks/title.php

When `strpos` cannot find a string, it will return `false`. Therefore all these checks need to compare against `false`, else this leads to false positives.
To test, use a theme that has neither `title-tag` support, nor `<title>` or `wp_title()` anywhere. You'll see that the checker will nonetheless throw these errors:
```
REQUIRED: The theme must not use the <title> tags. Found the tag in index.php.
REQUIRED: The theme must not use the <title> tags. Found the tag in inc/class-require-gutenberg.php.
REQUIRED: The theme must not use the <title> tags. Found the tag in functions.php.
REQUIRED: The theme must not call to wp_title(). Found wp_title() in index.php.
REQUIRED: The theme must not call to wp_title(). Found wp_title() in inc/class-require-gutenberg.php.
REQUIRED: The theme must not …
```

Fix false positives in title checks

---

checks/customizer.php

The Customizer checks can cause invalid regular expressions to be generated under certain situations. This PR fixes that while making the error code cleaner.

Fix invalid regular expression

---

checks/directories.php

Combines the logic and avoid false positives where .svn/.git/.hg/.bzr exist within a filename/file path but are not actually present in the theme.
An example of this would be having Theme Check installed in a WordPress install at `~/public_html/company.hg/`.
This also extends the `.hg` and `.bzr` checks to PHP files.
Fixes #193

Avoid false positives when .svn/.git/.hg/.bzr exists within the path to a theme.

---

checks/filesystem-http.php
checks/malware.php

This PR removes warnings about `file_get_contents()` and encourages it's usage over WP_Filesystem for general IO operations.
HTTP methods are also replaced with a new error message, to use the WordPress HTTP library instead.

Allow file_get_contents() and discourage usage of WP_Filesystem for basic IO tasks

---

checkbase.php
checks/fse-required-files.php

This code is "good enough", by design. It's supposed to make it easier to upload experimental themes to WordPress.org without having to add code just for the sake of passing the checker.
As FSE themes become more stable, the Theme Checker as well as the checks would need a larger re-organization. So this can be revisited as part of that change down the line.
See #279.

Adapt checks for Full-Site Editing themes

---

.gitattributes
.github/workflows/deploy.yml

The attached GitHub workflow deploys the plugin to the plugin directory using [10up's plugin deploy action](https://github.com/10up/action-wordpress-plugin-deploy).
It's triggered by a Release being created on GitHub.
To release a new version with this:
- update plugin header version string
- update readme.txt stable tag
- tag/release a release
- wait a few minutes and see it's updated on WordPress.org.

Add a deploy action, to push it to the WordPress.org plugin directory

---

checks/content-width.php

Not including content_width isn't _breaking_, so make it optional.

Lower content_width check to recommended

---

checks/gravatar.php

Because comments are no longer required, neither is supporting gravatars.
Reduce the level of the check from required to recommended.

Reduce the gravatar check to recommended

---

checks/class-file-check.php

Replaces https://github.com/WordPress/theme-check/pull/363

Remove filenames from the File_Check, allow development files

---

checks/class-style-tags-check.php

Template Editing is a new tag and added in WordPress.  Current version of Theme checks show it as REQUIRED.

Added Template Editing tag in allowed tags list

---

changelog.txt
checkbase.php
readme.txt

Allow `tc_filename()` to return theme-relative filenames when themes are loaded from custom directories, or are nested within other folders in wp-content/themes.
Fixes #369

Allow `tc_filename()` to return theme-relative filenames

---

checkbase.php
checks/class-fse-required-files-check.php

FSE themes are changing folders in https://github.com/WordPress/gutenberg/pull/36647
This PR adapts theme check accordingly.
It should only be merged after the linked PR is merged.

Update the FSE theme folders to the new proposed structure

---

checks/class-textdomain-check.php

This commit addresses issue #430. When a theme doesn't use any of the internationalization functions, the `TextDomain_Check` class doesn't account for an empty array of found domains.

Checks for empty textdomain array

---

checks/class-style-tags-check.php

Adding "style-variations" tag is missing from the valid theme tags.
Without this fix you get this warning on themes using that tag:
```
INFO Found wrong tag, remove style-variations from your style.css header.
```
The "style-variations" is valid feature tag documented here:
https://make.wordpress.org/themes/handbook/review/required/theme-tags/#features-tags
Fixes: #439

adding style-variations tag to the list of valid tags

---

checks/class-non-gpl-check.php

Non_GPL_Check check returns false when it fails
Fixes: https://github.com/WordPress/theme-check/issues/465

Non_GPL_Check check returns false when it fails

---

checkbase.php

Disable Block_Patterns_Check for block themes
https://github.com/matiasbenedetto/theme-check/blob/2052c6884f049589554be54c3b2e594aee07b4ce/checks/class-block-patterns-check.php
When checking block themes the messages below won't be printed.
This check prints these messages on block themes which doesn't seems to be needed:
```
RECOMMENDED
No reference to register_block_pattern was found in the theme. Theme authors are encouraged to implement custom block patterns as a transition to block themes.
RECOMMENDED
No reference to register_block_style was found in the theme. Theme authors are encouraged to implement new block styles as a transition to block themes.
```

Disable Block_Patterns_Check for block themes
