- checks/screenshot.php
https://make.wordpress.org/themes/handbook/review/required/#screenshot
> Increase screenshot size to 1200x900px

- checks/textdomain.php
> Translation bug fix

- readme.txt
Very minor link updates. Latest TRT handbook and removed `extend` from theme directory.
> TRT and directory link updates.

- checks/deprecated.php
https://codex.wordpress.org/Version_4.4#Deprecated
https://codex.wordpress.org/Version_4.5#Deprecated
> Update deprecated functions for 4.4 & 4.5

- checks/style_tags.php
> Update the check with the new tags

- checks/cdn.php
Check not only PHP files but also CSS files also for hardcoded CDN URL. Modified `cdn.php`.
> Check not only PHP files but also CSS files also for hardcoded CDN URL

- checks/adminbar.php
> The use of #wpadminbar should not fail the check

- checks/include.php
Fixes https://github.com/Otto42/theme-check/issues/158
> add ' and " to lookback in include regex.

- checks/style_tags.php
A maximum of 3 subject tags are allowed
> A maximum of 3 subject tags are allowed

- checks/style_tags.php
Close https://github.com/WordPress/theme-check/issues/178
@grappler There was an issue in merging with this branch, pretty sure due to my Git-screw-up, so I had to delete that branch. Hope this will do. :)
> Check if style.css is using one tag twice

- checks/navmenu.php
> Add check for redundant menu support declaration code

- checks/deprecated.php
add functions deprecated in 4.3, 4.4, 4.6, 4.7, 4.8, 4.9, 5.1
> add functions deprecated in 4.3 to 5.1

- checks/admin_menu.php
- checks/basic.php
- checks/plugin-territory.php
- checks/title.php
- checks/widgets.php
- main.php
> Replace old links

- checks/customizer.php
Add line numbers and name of settings to the sanitize callback check
#35
> Add line numbers to the sanitize callback check

- checks/title.php
File names will make it easier to find where the error is.
Solves #191
> Add file names to title checks

- checks/nongplsites.php
Checks if the theme includes resources from websites that does not use a GPL compatible license.
#212
**This must not be merged until we have a decision whether it needs to be a warning or a requirement.**
> Check for URLs to image sites with non GPL images

- checks/filenames.php
Add warnings for demo content files and phpcs.
#229
> Add warnings for demo content files and phpcs

- checks/siteurl.php
> Add an info check for site_url

- checks/plugin-territory.php
> Check for remove_action wp_head

- checks/style_needed.php
Checks style.css' header for the `Tested up to` & `Requires PHP` fields.
> Added `Tested up to` & `Requires PHP` sniffs for style.css

- checks/underscores.php
> Fixes a typo

- checks/script_tag.php
Fixes https://github.com/WordPress/theme-check/issues/149
It does not stop upload since there can be valid exceptions that needs manual review.
> Add a check for the <script> tag

- .github/workflows/phpcs.yml
- composer.json
- composer.lock
Looks like I fumbled the GitHub actions workflow, this PR should fix it.
> Fix the PHPCS action runner

- checks/block-patterns.php
> Add block patterns notice

- checks/textdomain.php
Include the twentytwentyone textdomain in the list of exceptions in TextDomainCheck
> Include the twentytwentyone textdomain

- checks/widgets.php
The checks are required and this PR updates the CSS class from `tc-recommended` to ` tc-required`.
> Update CSS classes for the widget checks

- checkbase.php
Remove duplicate PostThumbnailCheck, add Includecheck to checks that are not run on block themes.
> Update checks that are not run on block themes.

- checks/filenames.php
Remove unused check for recommended files in File_Checks filenames.php.
> Remove unused code

- theme-check.php
Fix issue reported by PHPstan:
`Parameter #4 $ver of function wp_enqueue_style expects bool|string|null, int given.`
> Update style version in load_styles() in theme-check.php

- checks/class-theme-support-check.php
File name changes and doc blocks for the theme support check
> File name changes and doc blocks

- checks/class-admin-menu-check.php
Reduce menu check from required to recommended
> Reduce menu check from required to recommended

- checks/class-generated-check.php
Reduces the generated themes check from required to warning. Updates the warning message.
> Reduce the generated themes check to warning

- checks/class-deprecated-check.php
- checks/class-deprecated-param-check.php
Reduces the deprecated checks from required to warning.
> Reduce the deprecated checks from required to warning

- checks/class-style-tags-check.php
Set the checks that checks for deprecated and incorrect tags to info, since they are not breaking.
> Reduce style-tags check

- checks/class-plugin-territory-check.php
Removes the dashboard widget requirement
https://github.com/WPTT/Theme-Requirements/issues/10#issuecomment-862347955
> Remove the dashboard widget requirement

- changelog.txt
New version 20211203 changelog maintained
> Updated changelog file

- theme-check.php
New version of theme check plugin 20211203
> Update plugin version

- checks/class-theme-support-check.php
> Allow more whitespace in add_theme_support() call

- checks/class-style-css-header-check.php
This PR will check if Update URI will be present in the style.css header or not.
If present, it will display a REQUIRED message.
> Update URI check added

- readme.txt
Added kafleg as contributor in readme.txt
> Add contributor

- theme-check.php
Updated plugin to 20230412 after checking with 6.2 and fixing other issues.
> Update theme-check version

- readme.txt
This PR will change the tested up to and other changes in readme file.
> Tested Up To 6.3

- checks/class-comments-check.php
- checks/class-constants-check.php
- checks/class-deprecated-param-check.php
- checks/class-deregister-check.php
- checks/class-non-gpl-check.php
added comments for translators in multiple files
> added comments for translators
